export const filterData = [
    {name: "Đồ ăn nhanh", image: require('../assets/fastfood.png'), id: "0"},
    {name: "Ăn vặt", image: require('../assets/snack.png'), id: "1"},
    {name: "Đồ uống", image: require('../assets/drink.png'), id: "2"},
    {name: "Cơm", image: require('../assets/rice.png'), id: "3"},
    {name: "Ăn chay", image: require('../assets/vegetarianfood.png'), id: "4"},
    {name: "Hải sản", image: require('../assets/seafood.png'), id: "5"},
];

export const filterData2 = [{name:"Fast food",image:'https://bukasapics.s3.us-east-2.amazonaws.com/chicken.png' , id:"0"},
{name:"Burgers",image: 'https://bukasapics.s3.us-east-2.amazonaws.com/macdo.png',id:"1"},
{name:"Salads",image:"https://bukasapics.s3.us-east-2.amazonaws.com/nandos.png",id:"2"},
{name:"Hotdog",image: "https://bukasapics.s3.us-east-2.amazonaws.com/pizza.png",id:"3"},
{name:"Chinese",image:"https://bukasapics.s3.us-east-2.amazonaws.com/pizza6.png",id:"4"},
{name:"Mexican",image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate1.png",id:"5"},  
{name:"Sea food",image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate2.png",id:"6"},
{name:"Chinese Food",image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png",id:"7"},
{name:"Mexican pie",image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png",id:"8"},  
{name:"Ocean dish",image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png",id:"9"},
];


export const restaurantsData = [
    {restaurantName:"Mc Donalds", farAway:"21.2",
    businessAddress:"123 Đ. Nguyễn Huệ, Bến Nghé, Quận 1",images:'https://mcdonalds.vn/uploads/2018/news/0-02-06-9cb7c8f2e59fd00a29189138e205ed041e2d95b5e7dadecd91169e4a997df243_9b36edeb455d500d.jpg',
    averageReview:4.9,numberOfReview:272,coordinates : {lat: -26.1888612, lng: 28.246325} ,discount:10,deliveryTime:15,
    collectTime:5, foodType:"Burgers, Wraps,Milkshakes..." ,
    productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
    {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
     price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
      ],
    id:0},
    
    {restaurantName:"KFC", farAway:"12.7",businessAddress:"265 Âu Cơ, Phường 5, Quận 11",
    images:'https://tuyendung.kfcvietnam.com.vn/Data/Sites/1/News/50/01-red-annule.png',
    averageReview:4.3, numberOfReview:306, coordinates : {lat: -26.1891648, lng: 28.2441808},
    discount:20,deliveryTime:30,collectTime:10, foodType:"Chicken,Chicken wings... ",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
    {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},
    {name:"Chicken Burger", price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
        ],
    id:1},
    
    {restaurantName:"Texas", farAway:"5",businessAddress:"463 Đ. Sư Vạn Hạnh, Phường 12, Quận 10",
    images:'https://texaschickenvn.com/vnt_upload/product/07_2023/Combo_Vui_Ve_B.png',
     coordinates :{ lat: -26.1886781, lng: 28.244879}, averageReview: 4.9,numberOfReview: 1272,
      discount:12, deliveryTime:25,collectTime:15,foodType:"Flame grilled beef Burgers",
     productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
      {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
       price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
        ],
     id:2},
    
    {restaurantName:"Pizza 4P", farAway:"7",businessAddress:"30 Đ. Tân Thắng, Sơn Kỳ, Tân Phú",
    images:'https://assets-global.website-files.com/5fb85f26f126ce08d792d2d9/6348ededebfe4a1260653ab0_Before_Cafe-4Ps.jpg',
    averageReview:4.3, numberOfReview:700, coordinates: {lat: -26.1845336, lng: 28.2481691},
    discount:null,deliveryTime:20,collectTime:10,foodType:"Chicken pizza, Vegetarian pizza...",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png"},
      {name:"Big Mac", price:50.80,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png"},{name:"Chicken Burger",
       price:70,image:"https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png"},
        ],
    id:3},
]